name: Deploy Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/deploy_infra.yaml'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install AZD
      run: |
        curl -fsSL https://aka.ms/install-azd.sh | bash
      working-directory: infra

    - name: Deploy infrastructure
      env:
        AZURE_LOCATION: 'eastus2'
        AZURE_ENV_NAME: 'production'
        VNET_ENABLED: False
        AZURE_RESOURCE_GROUP_NAME: 'rg-mcp-demo'
      run: |
        azd provision --environment production
      working-directory: infra