name: Deploy Function App

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore src/Monkey/Monkey.sln

    - name: Build project
      run: dotnet build src/Monkey/Monkey.sln --configuration Release

    - name: Publish project
      run: dotnet publish src/Monkey/Monkey.sln --configuration Release --output ./publish

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Deploy to Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --resource-group rg-mcp-demo \
          --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
          --src ./publish
      env:
        AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
